ezviz_alarm_sound:
  description: "Set movement warning sounds."
  fields:
    level:
      description: "Sound level (2 is disabled, 1 intensive, 0 software)."
      example: "0"
    serial:
      description: "Enter serial of Camera."
      example: "D6666666"

ezviz_wake_device:
  description: "This can also be used to wake device from hibernation."
  fields:
    serial:
      description: "Enter serial of Camera."
      example: "D6666666"

ezviz_ptz:
  description: "Moves the camera to the direction, with defined speed"
  fields:
    serial:
      description: "Enter serial of Camera."
      example: "D6666666"
    direction:
      description: "Direction (up, down, left, right)."
      example: "up"
    speed:
      description: "Speed of the movement (from 1 to 9)."
      example: "5"

ezviz_switch_set:
  description: "Switches camera options or device switches."
  fields:
    serial:
      description: "Enter serial of Camera."
      example: "D6666666"
    switch:
      description: "Switch to set. Choices are : SOUND, INFRARED_LIGHT, LIGHT, PRIVACY, SLEEP , MOBILE_TRACKING."
      example: "LIGHT"
    enable:
      description: "Enter 1 or 0 (0=disable, 1=enable)."
      example: "0"

ezviz_set_alarm_detection_sensibility:
  description: "Sets the detection sensibility level."
  fields:
    serial:
      description: "Enter serial of Camera."
      example: "D6666666"
    level:
      description: "Sensibility level (1-6) for device (type 0) or (1-100) for cameras (type 3)."
      example: "0"
    type:
      description: "Type of detection. Options : 0 - Device or 3 - Camera"
      example: "3"