ezviz_ptz:
  description: Moves the camera to the direction, with defined speed
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    direction:
      description: Direction (up, down, left, right).
      example: "up"
    speed:
      description: Speed of the movement (from 1 to 9).
      example: "5"

ezviz_switch_audio:
  description: Switch the camera audio on.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_switch_ir:
  description: Switch the camera infra red led on.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_switch_privacy:
  description: Switch the camera privacy on.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_switch_state:
  description: Switch the camera state led on/off.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_switch_sleep:
  description: Switch the camera movement following on.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_switch_follow_move:
  description: Switch the camera movement following on.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
    cmd:
      description: Enter 1 or 0.
      example: "0"

ezviz_get_detection_sensibility:
  description: Fetches detection sensibility. This can also be used to wake device from hibernation.
  fields:
    serial:
      description: Enter serial of Camera.
      example: "D6666666"
